### PR TITLE
backend plugin

### PR DESCRIPTION
**Pull request by mtanda**
Try to support backend plugin.
Not tested well.

### CODE REVIEW

**Comment by mweiden** [comment]
@mtanda could you say a little bit more (or add documentation) on how to configure this? Is it with the `GOOGLE_APPLICATION_CREDENTIALS` environment variable?

**Comment by mtanda** [comment]
hmm, sorry. I didn't test it service account.
According to api guide, it says `use DefaultClient`.
https://github.com/google/google-api-go-client/blob/master/GettingStarted.md

And I do so.
https://github.com/mtanda/grafana-google-stackdriver-datasource/pull/24/files#diff-4fadc66382f2a85543cefe051bedef99R29

**Comment by mtanda** [comment]
https://github.com/golang/oauth2/blob/dd5f5d8e78ce062a4aa881dff95a94f2a0fd405a/google/default.go#L23
https://github.com/golang/oauth2/blob/dd5f5d8e78ce062a4aa881dff95a94f2a0fd405a/google/default.go#L45

`DefaultClient` read `GOOGLE_APPLICATION_CREDENTIALS`, so I guess you need to set it...

**Comment by gavinreaney** [comment]
@mtanda: Just FYI: we (infostellar) were able to authenticate fine with GOOGLE_APPLICATION_CREDENTIALS and a service account. Thanks for providing this useful plugin.

**Comment by mtanda** [comment]
@gavinreaney Thanks for your testing and feedback :-)
I can't test all case, so it's really helpful for me.

**Comment by gavinreaney** [comment]
One issue I saw is that in some cases the query response size was too large for gRPC. In our case, the gRPC size limit is 4M (maybe we can control this limit but I didn't check).

This issue happened for counters that are updated frequently and when querying a large time range.

If you see cases where a query fails when making the time range longer, then this may be the cause (there is an error message in the grafana server log when this happens but no useful error message on the JS side).

The workaround was to apply alignment and reduction to decrease the size of the response.

**Comment by mtanda** [comment]
Thanks for sharing workaround!
If too many time series are matched for the query, we may hit the limit size.
I escalate this issue to Grafana core.

**Pull request merged**
